import {Comment} from "@/types";

export const comments: Comment[] = [
  {
    id: "1",
    content: "This is a great post! Thanks for sharing.",
    authorName: "John Doe",
    authorId: "user1",
    authorImage: "",
    parentId: undefined,
    replies: ["2", "3"],
    creation: "2024-01-15T10:30:00Z",
    modified: "2024-01-15T10:30:00Z",
    upvotes: 15,
    downvotes: 2,
    canEdit: false,
    canDelete: false,
  },
  {
    id: "2",
    content: "I completely agree with your point!",
    authorName: "Jane Smith",
    authorId: "user2",
    authorImage: "",
    parentId: "1",
    replies: [],
    creation: "2024-01-15T11:00:00Z",
    modified: "2024-01-15T11:00:00Z",
    upvotes: 8,
    downvotes: 0,
    canEdit: false,
    canDelete: false,
  },
  {
    id: "3",
    content: "Thanks for the detailed explanation.",
    authorName: "Mike Johnson",
    authorId: "user3",
    authorImage: "",
    parentId: "1",
    replies: [],
    creation: "2024-01-15T12:15:00Z",
    modified: "2024-01-15T12:15:00Z",
    upvotes: 5,
    downvotes: 1,
    canEdit: false,
    canDelete: false,
  },
];
